### ISSUE TITLE
double hits if pipeline of queries is used

### ISSUE THREAD

**Issue by gertjanvannoord** [rug-compling/dact#125]
This query:

//node[@lemma="niet"] +|+ //node[@lemma="Nasser"]

will count occurrences of Nasser twice if a sentence contains two occurrences of "niet".

This can be observed both in the statistics widget and the Hits-column of the sentences widget. 

use /net/corpora/LassyDevelop/lassy.small to get the same result as I

**Comment by danieldk** [comment]
Dact 2.2 is released and fixes this correctly.
