### ISSUE TITLE
Missing attributes

### ISSUE THREAD

**Issue by pebbe** [rug-compling/dact#130]
In alpino_ds.dtd ontbreken vijf attributen die door Alpino worden gegenereerd:

 iets
 pron
 personalized
 rnum
 stype

**Comment by danieldk** [comment]
Dact leest ze uit de DTD, dus het lijkt erop dat de DTD outdated is?

http://www.let.rug.nl/~dekok/svn/filedetails.php?repname=Alpino&path=%2FTreebank%2Falpino_ds.dtd

@gertjanvannoord

**Comment by gertjanvannoord** [comment]
klopt, gisteren toegevoegd in Alpino, vandaag in svn, morgen
in git ...

GJ

**Comment by danieldk** [comment]
On Thu, Sep 24, 2015 at 10:05 AM, gertjanvannoord <notifications@github.com>
wrote:

> klopt, gisteren toegevoegd in Alpino, vandaag in svn, morgen
> in git ...
>

Ah, perfect! Dan ook snel in Dact ;).

**Comment by danieldk** [comment]
Fixed in 6994a260a830910dcba99589414f149fc71745ca.
