### ISSUE TITLE
add constraint from statistics tab: wrong results

### ISSUE THREAD

**Issue by gertjanvannoord** [rug-compling/dact#132]
After a query in the statistics tab, you can double-click on one of the obtained values. A new query is then constructed where the attribute with the corresponding value is added to the query. 

E.g., original query
//node[@word="bezorgd" or @word="bezorgde"]
and we are counting values of @postag

If I click on the value "WW(vd,vrij,zonder)", then the new query becomes:

//node[@word="bezorgd" or @word="bezorgde" and @postag="WW(vd,vrij,zonder)"]

this is wrong! Because this reads "A or (B and C)"  instead of the intended "(A or B) and C".

**Comment by danieldk** [comment]
Ideally, we'd parse the query with XQilla, modify the query AST and serialize back to a string, but I don't see an obvious way to do this with the XQilla API.

So I guess we have to do some good old string manipulation :p.
