### ISSUE TITLE
Crash with cancel button

### ISSUE THREAD

**Issue by pebbe** [rug-compling/dact#134]
I got Dact running on three machines, on each machine compiled from the
latest sources:

 1. Debian GNU/Linux 9
 2. Ubuntu 14.04.5 LTS
 3. Ubuntu 16.04.3 LTS

Dact runs fine on the first two, but crashes on the third. (This also
happened with older versions of Dact.) The crash happens when opening a
local file. A small window appears, with nothing but an input field and
a cancel button. Clicking the cancel button crashes Dact.

This is the output in the terminal:

```
QObject::connect: No such slot DactApplication::showWebserviceWindow()
QObject::connect:  (sender name:   'webserviceAction')
Read history, but it is not a QStringList.
QObject::connect: No such slot DactApplication::showWebserviceWindow()
QObject::connect:  (sender name:   'webserviceAction')
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
setNativeLocks failed: Resource temporarily unavailable
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
Segmentation fault (core dumped)
```

All but the first line are printed before clicking the cancel button.

**Comment by danieldk** [comment]
Does this happen when you select the local corpus in the 'Open Corpus' dialog? Or when you select 'Open local file' from this dialog?

Could it be that the small window actually contains a progress bar (at 0%) rather than an input field?

During some Qt upgrade,  progress dialogs would show up all the time, I thought that I had solved all instances of this problem, but may have missed something.

**Comment by danieldk** [comment]
I changed my build options and can now reproduce this.

**Comment by danieldk** [comment]
The last commit should fix this error. This bug arises because of a change in QProgressDialog behavior in Qt 5.5.

**Comment by pebbe** [comment]
Yes, this fixed it. Thanks.
